version: '3.8'
services:
  sqlite3:
    image: nouchka/sqlite3:latest
    container_name: sqlite3
    stdin_open: true
    tty: true
    volumes:
      - ./sqlite:/root/db
    environment:
      - SQLITE_DB=db.sqlite3
  web:
    build: .
    container_name: drf_app
    env_file:
      - ./drftt/.env
    volumes:
      - ./drftt
    ports:
      - 8000:8000
    depends_on:
      - sqlite3



