version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./drftt/.env
  web:
    build: .
    env_file:
      - ./drftt/.env
    volumes:
      - ./code
    ports:
      - 8000:8000
    depends_on:
      - db



