version: '3.8'
volumes:
  data: {}
services:
  db:
    container_name: postgres
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - ./drftt/.env
  web:
    build: .
    container_name: drf
    env_file:
      - ./drftt/.env
    volumes:
      - data
    ports:
      - 8000:8000
    depends_on:
      - db



