version: '3.8'
volumes:
  data: {drftt_vol}
services:
  db:
    container_name: postgres
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build: .
    container_name: drf-app
    env_file:
      - .env
    volumes:
      - data
    ports:
      - 8000:8000
    depends_on:
      - db



