version: '3.8'
services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    env_file:
      - ./drftt/.env
    restart: always
    volumes:
      - ./db_drftt:/var/lib/mysql
  web:
    build: .
    container_name: drf_app
    env_file:
      - ./drftt/.env
    volumes:
      - ./drftt

    ports:
      - 8000:8000
    depends_on:
      - db

