# Generated by Django 4.0.5 on 2022-07-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_game_gamelevel_alter_gamesummary_table_teamanswers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplay',
            name='getted_promt_counter',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gameplay',
            name='wrong_counter_answer',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
