# Generated by Django 4.0.5 on 2022-07-08 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_gameplay_getted_promt_counter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplay',
            name='data',
        ),
    ]
