# Generated by Django 4.0.5 on 2022-07-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_gameplay_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPlace',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('place', models.BigIntegerField(null=True)),
                ('total_finished', models.PositiveIntegerField(blank=True, null=True)),
                ('summ_penalty', models.DecimalField(decimal_places=11, max_digits=17, null=True)),
            ],
            options={
                'db_table': 'team_place',
                'managed': False,
            },
        ),
    ]
