# Generated by Django 4.0.5 on 2022-07-08 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_teamplace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameSummary',
        ),
    ]
