# Generated by Django 4.0.5 on 2022-07-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_gamesummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelevel',
            name='number',
            field=models.PositiveIntegerField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='gameplay',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='promt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teamanswers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
