# Generated by Django 4.0.5 on 2022-07-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_gamelevel_number_alter_gameplay_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelevel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
