# Generated by Django 4.0.5 on 2022-07-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_gamelevel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelevel',
            name='promt1',
            field=models.CharField(db_index=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='gamelevel',
            name='promt2',
            field=models.CharField(db_index=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='gamelevel',
            name='promt3',
            field=models.CharField(db_index=True, max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='Promt',
        ),
    ]
